/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Health;

import Business.EcoSystem;
import Business.Enterprise.HealthEnterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class HealthAdminWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form HealthAdminWorkAreaPanel
     */
     JPanel userProcessContainer;
    HealthEnterprise enterprise;
    //WealthEnterprise enterprise1;
    EcoSystem ecosystem;
   
    public HealthAdminWorkAreaPanel(JPanel userProcessContainer,EcoSystem ecosystem, HealthEnterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        this.enterprise=enterprise;
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageOrganizationJButton = new javax.swing.JButton();
        manageEmployeejButton = new javax.swing.JButton();
        userJButton = new javax.swing.JButton();
        imgLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(164, 208, 204));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("     Health Admin Role");
        add(jLabel1);
        jLabel1.setBounds(530, 120, 360, 34);

        manageOrganizationJButton.setBackground(new java.awt.Color(189, 94, 41));
        manageOrganizationJButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        manageOrganizationJButton.setText("Manage Organization");
        manageOrganizationJButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(189, 94, 41)));
        manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButtonActionPerformed(evt);
            }
        });
        add(manageOrganizationJButton);
        manageOrganizationJButton.setBounds(560, 240, 290, 60);

        manageEmployeejButton.setBackground(new java.awt.Color(189, 94, 41));
        manageEmployeejButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        manageEmployeejButton.setText("Manage Employee");
        manageEmployeejButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(189, 94, 41)));
        manageEmployeejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeejButtonActionPerformed(evt);
            }
        });
        add(manageEmployeejButton);
        manageEmployeejButton.setBounds(560, 360, 290, 60);

        userJButton.setBackground(new java.awt.Color(189, 94, 41));
        userJButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        userJButton.setText("Manage User");
        userJButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(189, 94, 41)));
        userJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userJButtonActionPerformed(evt);
            }
        });
        add(userJButton);
        userJButton.setBounds(560, 490, 290, 60);

        imgLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sindhu\\Documents\\AED\\finalproject\\EcoSystem (1)\\EcoSystem\\src\\health.jpeg")); // NOI18N
        add(imgLabel);
        imgLabel.setBounds(40, -30, 1440, 890);
    }// </editor-fold>//GEN-END:initComponents

    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed
        // TODO add your handling code here:
         ManageHealthOrganizationJPanel manageOrganizationJPanel = new ManageHealthOrganizationJPanel(userProcessContainer,ecosystem,enterprise);
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed

    private void manageEmployeejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeejButtonActionPerformed
        // TODO add your handling code here:
        ManageHealthEmployeeJPanel manageEmployeeJPanel = new ManageHealthEmployeeJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_manageEmployeejButtonActionPerformed

    private void userJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userJButtonActionPerformed
        // TODO add your handling code here:
        ManageHealthUserAccountJPanel muajp = new ManageHealthUserAccountJPanel(userProcessContainer, enterprise,ecosystem);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_userJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageEmployeejButton;
    private javax.swing.JButton manageOrganizationJButton;
    private javax.swing.JButton userJButton;
    // End of variables declaration//GEN-END:variables
}
