/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.EnterpriseAdminDirectory;
import Business.EnterpriseDirectory;
import Business.NetworkDir;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Sindhu
 */
public class AdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form AdminWorkArea
     */
    private EnterpriseAdminDirectory enterpriseAdminDirectory;
    private EnterpriseDirectory enterpriseDirectory;
    private JPanel userInteractionPanel;
    private NetworkDir networkDir;
    public AdminWorkArea(JPanel userInteractionPanel) {
        initComponents();
        enterpriseAdminDirectory = new EnterpriseAdminDirectory();
        networkDir = new NetworkDir();
        enterpriseDirectory = new EnterpriseDirectory();
        this.userInteractionPanel = userInteractionPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        networkBtn = new javax.swing.JButton();
        enterpriseBtn = new javax.swing.JButton();
        entAdminBtn = new javax.swing.JButton();

        networkBtn.setText("Manage Network");
        networkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkBtnActionPerformed(evt);
            }
        });

        enterpriseBtn.setText("Manage Enterprise");
        enterpriseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseBtnActionPerformed(evt);
            }
        });

        entAdminBtn.setText("Manage Enterprise Admin");
        entAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entAdminBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(entAdminBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(networkBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enterpriseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(networkBtn)
                .addGap(45, 45, 45)
                .addComponent(enterpriseBtn)
                .addGap(52, 52, 52)
                .addComponent(entAdminBtn)
                .addContainerGap(161, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void networkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkBtnActionPerformed
        // TODO add your handling code here:
        NetworkPanel networkPanel = new NetworkPanel(userInteractionPanel,networkDir);
        userInteractionPanel.add("NetworkPanel",networkPanel);
        CardLayout layout = (CardLayout)userInteractionPanel.getLayout();
        layout.next(userInteractionPanel);
    }//GEN-LAST:event_networkBtnActionPerformed

    private void entAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entAdminBtnActionPerformed
        // TODO add your handling code here:
        ConfigureEnterpriseAdminPanel entAdminPanel = new ConfigureEnterpriseAdminPanel(enterpriseAdminDirectory,networkDir,userInteractionPanel,enterpriseDirectory);
        userInteractionPanel.add("AdminConfigPanel",entAdminPanel);
        CardLayout layout = (CardLayout)userInteractionPanel.getLayout();
        layout.next(userInteractionPanel);
    }//GEN-LAST:event_entAdminBtnActionPerformed

    private void enterpriseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseBtnActionPerformed
        // TODO add your handling code here:
        EnterprisePanel entPanel = new EnterprisePanel(userInteractionPanel,networkDir,enterpriseDirectory);
        userInteractionPanel.add("AdminConfigPanel",entPanel);
        CardLayout layout = (CardLayout)userInteractionPanel.getLayout();
        layout.next(userInteractionPanel);
    }//GEN-LAST:event_enterpriseBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton entAdminBtn;
    private javax.swing.JButton enterpriseBtn;
    private javax.swing.JButton networkBtn;
    // End of variables declaration//GEN-END:variables
}
