/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EventManagerWorkArea;

import Business.EcoSystem;
import Business.Enterprise.WelfareEnterprise;
import Business.Event.Event;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sindhu
 */
public class EventManagerWorkAreaPanel extends javax.swing.JPanel {

     WelfareEnterprise enterprise;
    EcoSystem ecosystem;
    JPanel userProcessContainer;
    Organization organization;
    /**
     * Creates new form EventManagerWorkAreaPanel
     */
   
    public EventManagerWorkAreaPanel(JPanel userProcessContainer, EcoSystem system, WelfareEnterprise enterprise, Organization organization, UserAccount account) {
       initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.ecosystem = system;
        this.organization = organization;
        eventJTable.getTableHeader().setFont(new Font("TImes New Roman",Font.BOLD,18));
        eventJTable.setRowHeight(30);
        eventJTable.setRowMargin(10);
        populateTable();
    }

   
    
     public void populateTable(){
        
        DefaultTableModel model = (DefaultTableModel)eventJTable.getModel();
        
        if(enterprise.getEventDirectory()!=null){
            for(Event event:enterprise.getEventDirectory().getEventDirectory()){
                if(event.getEventId()!=0){
                   Object[] row = new Object[model.getColumnCount()];
                    row[0] = event.getEventId();
                    row[1] = event.getEventName();
                    row[2] = event.getEventOrganiser();
//                    row[3] = event.getFundsCollected();
                    model.addRow(row); 
                }
            }
        }
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        eventJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        eventnameJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fundscollectedJTextField1 = new javax.swing.JTextField();
        addJButton = new javax.swing.JButton();
        imgLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(193, 161, 171));
        setLayout(null);

        eventJTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        eventJTable.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        eventJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Event Id", "Event Name", "Event Organiser"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        eventJTable.setRowHeight(20);
        jScrollPane1.setViewportView(eventJTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(580, 210, 523, 140);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Event Name:");
        add(jLabel2);
        jLabel2.setBounds(670, 390, 150, 28);

        eventnameJTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        eventnameJTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(102, 0, 102)));
        add(eventnameJTextField);
        eventnameJTextField.setBounds(840, 380, 160, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Funds Collected:");
        add(jLabel6);
        jLabel6.setBounds(630, 450, 180, 28);

        fundscollectedJTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(102, 0, 102)));
        add(fundscollectedJTextField1);
        fundscollectedJTextField1.setBounds(840, 450, 160, 40);

        addJButton.setBackground(new java.awt.Color(153, 102, 0));
        addJButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addJButton.setText("Add  Event");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        add(addJButton);
        addJButton.setBounds(860, 530, 120, 40);

        imgLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sindhu\\Documents\\AED\\finalproject\\EcoSystem (1)\\EcoSystem\\src\\img-4.jpg")); // NOI18N
        add(imgLabel);
        imgLabel.setBounds(320, 150, 1038, 560);
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
       DefaultTableModel model = (DefaultTableModel)eventJTable.getModel();
       
       int event_id = model.getRowCount()+1;
        String event_name= eventnameJTextField.getText();
        String event_fundscollected= fundscollectedJTextField1.getText();
        
        if(eventnameJTextField.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter a event name","Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
        enterprise.getEventDirectory().addEvent(event_id,event_name,enterprise.getName(),event_fundscollected);
        populateTable();
        JOptionPane.showMessageDialog(null, "Event Added Successfully");
        }
        
       
    }//GEN-LAST:event_addJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JTable eventJTable;
    private javax.swing.JTextField eventnameJTextField;
    private javax.swing.JTextField fundscollectedJTextField1;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
