/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Beneficiaries.Beneficiary;
import Business.EcoSystem;
import Business.Enterprise.WelfareEnterprise;
import Business.Network.Network;
import Business.Organization.WelfareOrganization;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Set;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Sindhu
 */
public class ViewStatisticsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewStatisticsJPanel
     */
   
    private JPanel userProcessContainer;
    private EcoSystem system;
    ViewStatisticsJPanel(JPanel userProcessContainer, EcoSystem ecosystem) {
       initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = ecosystem;
        createChartData();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void createChartData(){
        HashMap<String,Integer> dataMap = new HashMap<String,Integer>();
        HashMap<String,Integer> dataBenMap = new HashMap<String,Integer>();
        int no_of_ben = 0;
        int maxCount = 0;
        for(Network net:system.getNetworkList()){
            for(WelfareEnterprise ent:net.getEnterpriseDirectory().getWelfareEnterpriseList()){
                for(WelfareOrganization org:ent.getWelfareOrganizationDirectory().getWelfareOrganizationList()){
                    if(!ent.getName().equals("Admin") && org.getName().equals("Beneficiary Organization")){
                        dataMap.put(String.valueOf(ent),org.getBeneficiaryDirectory().getBeneficiaryDirectory().size());
                        for(Beneficiary ben:org.getBeneficiaryDirectory().getBeneficiaryDirectory()){
                            if(ben.getStatus()!=null){
                                no_of_ben++;
                            }
                        }
                        maxCount = no_of_ben;
                        no_of_ben = 0;
                        dataBenMap.put(String.valueOf(ent),maxCount);
                    }
                }   
            }
        }
        populateBarChart(dataMap);
        populatePieChart(dataBenMap);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(193, 161, 171));

        Panel1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(814, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(597, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void populateBarChart(HashMap<String,Integer>dataMap){
        DefaultCategoryDataset dcd = new DefaultCategoryDataset();
        Set keys = dataMap.keySet();
        Iterator entIterator = keys.iterator();
        while(entIterator.hasNext()){
            String entname = String.valueOf(entIterator.next());
            int no_of_users = dataMap.get(entname);
            dcd.setValue(no_of_users,"No. of Beneficiaries",entname);
        }
        JFreeChart chart = ChartFactory.createBarChart3D("Enrolled Beneficiary record","Enterprise Name","No. of Beneficiaries",dcd, PlotOrientation.VERTICAL, true, true, false);
        CategoryPlot plot = chart.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.BLACK);
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setVisible(true);
        Panel1.removeAll();
        Panel1.add(chartPanel,BorderLayout.CENTER);
        Panel1.validate();
        Panel1.setVisible(true);
    }
    
    private void populatePieChart(HashMap<String,Integer>dataBenMap){
         DefaultPieDataset dcd = new DefaultPieDataset();
        Set keys = dataBenMap.keySet();
        Iterator entIterator = keys.iterator();
        while(entIterator.hasNext()){
            String entname = String.valueOf(entIterator.next());
            int no_of_users = dataBenMap.get(entname);
            dcd.setValue(entname,no_of_users);
        }
        JFreeChart chart = ChartFactory.createPieChart3D("Beneficiary Record",dcd, true, true, true);
        PiePlot3D plot =(PiePlot3D) chart.getPlot();
        ChartPanel chartPanel1 = new ChartPanel(chart);
        chartPanel1.setVisible(true);
        Panel1.setLayout(new GridLayout());
        Panel1.add(chartPanel1);
        Panel1.validate();
        Panel1.setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    // End of variables declaration//GEN-END:variables
}
